### ISSUE TITLE
Incorrect Linter CWD on Mac OSX

### ISSUE THREAD

**Issue by jwalk511** [purduesigbots/pros-atom#1]
PROS linter unable to find "main.h" on PROS package for Mac OS X El Capitan.

**Comment by jwalk511** [comment]
Issue due to fact that CWD defaults to path of first project open in Atom, not path of current project.

**Comment by edjubuh** [comment]
The relevant problem line is [L28 of lint.coffee](https://github.com/purduesigbots/pros-atom/blob/e1756a4af359b506c6152bd44eaaa08442d60523/lib/lint.coffee#L28) 
`cwd = atom.project.getPaths()[0]`
This line should have some more intelligent processing to determine what project the currently opened file truly originates from.
