### ISSUE TITLE
Any thoughts of providing an extension for VS Code similar to what is provided for Atom

### ISSUE THREAD

**Issue by KZeronimo** [purduesigbots/pros-atom#15]
Question

**Comment by edjubuh** [comment]
We extensively researched different IDEs during our discussion of moving from Eclipse, and settled on Atom. We did research VS Code, but at this point in time, extensions for VS Code are not on our roadmap. However, we do encourage community contributions to the PROS environment and would be happy to discuss how the atom plugins were developed.

**Comment by edjubuh** [comment]
We extensively researched different IDEs during our discussion of moving from Eclipse, and settled on Atom. We did research VS Code, but at this point in time, extensions for VS Code are not on our roadmap. However, we do encourage community contributions to the PROS environment and would be happy to discuss how the atom plugins were developed.
