### ISSUE TITLE
Pros project not being created

### ISSUE THREAD

**Issue by kmindspark** [purduesigbots/pros-atom#16]
#### Expected Behavior:
Project created
#### Actual Behavior:
Failed to create PROS project.
#### System information:
Operating System:  (Windows, OS X, Ubuntu)

Atom Version: (Atom Version)

Plugin Version: (Plugin Version)

**Comment by jabibi100** [comment]
@kmindspark can you please complete the form and provide as many details as possible. Until then we will not be able to proceed in helping you debug this issue.

**Comment by kmindspark** [comment]
Hi, I have another thread which details the error message I get just when trying to open atom, before even trying to create a new project. Thanks :)

**Comment by HotelCalifornia** [comment]
#17 seems to supercede this issue
