### ISSUE TITLE
No Text on PROS CLI

### ISSUE THREAD

**Issue by extension5525A** [purduesigbots/pros-atom#50]
#### System information: Widows 10
Operating System:  (Windows, OS X, Ubuntu)

PROS Version: (run `pros --version`) Not sure but downloaded it within the past week from the website.

#### Screenshots/Output Dumps/Stack Traces
![image](https://user-images.githubusercontent.com/28921580/29150640-ede90bc2-7d49-11e7-8220-94d7e4d8d893.png)

**Comment by HotelCalifornia** [comment]
Can you be more specific with respect to "any interaction"? What interactions did you try?

Also, can you open up a command prompt (type "cmd" into the search bar and it should be the first result) and run `pros --version`? The reason we ask users to do so is not only to report the version, but also to check that the PROS CLI has been properly installed.

In your screenshot, it looks like you have some package updates-- can you try updating them and see if that fixes your issue?

**Comment by extension5525A** [comment]
Well I tried to upload the project, type in random words into the line like when you click the keyboard button on the top left. It usually tells me that is a false command but nothing happened. I also tried to open the serial window and that changed nothing also. It is version 2.5.1

**Comment by extension5525A** [comment]
The updates is what fixed it thanks. Its resolved now.
