### ISSUE TITLE
how to open autocomeple?

### ISSUE THREAD

**Issue by 3038922** [purduesigbots/pros-atom#58]
Excuse me
I am a student,i come form china .my englist is poor.
I can't use autocomeple.
How to set up?autocomeple flags?

**Comment by 3038922** [comment]
![image](https://user-images.githubusercontent.com/33926386/33675423-7395266a-daed-11e7-940a-ada10a600ec2.png)

**Comment by 3038922** [comment]
I want to enter motoSet(1,127) ; ,but  only main and mark.

**Comment by edjubuh** [comment]
Autocomplete gives you suggestions once you type 3 or more characters. Do you see `motorSet` once you type `mot`? If so, I can give you instructions to decrease the number of characters required so you see suggestions starting at 1 or 2 characters.

**Comment by 3038922** [comment]
![image](https://user-images.githubusercontent.com/33926386/33676174-ea160118-daef-11e7-800c-45966a2c5e00.png)
I've been reloading many times. I think it's my system setting problem.

**Comment by 3038922** [comment]
![image](https://user-images.githubusercontent.com/33926386/33676257-3a18a1b6-daf0-11e7-9748-d0fb364313af.png)

**Comment by edjubuh** [comment]
OK, can you run Command Prompt and type `echo %PATH%`? You should see something like `C:\Program Files\PROS\llvm\bin` in the list.

**Comment by 3038922** [comment]
![image](https://user-images.githubusercontent.com/33926386/33676474-c883c80e-daf0-11e7-9f43-ba61ce07ea1d.png)

**Comment by 3038922** [comment]
![image](https://user-images.githubusercontent.com/33926386/33676512-dee078d6-daf0-11e7-883f-9307034215a9.png)

**Comment by edjubuh** [comment]
Ah, it looks like you're not using our distributed version of PROS Editor which includes the necessary dependencies. We fully support using Atom the way you have installed, but you'll need to install clang [here](http://releases.llvm.org/5.0.0/LLVM-5.0.0-win64.exe).

**Comment by 3038922** [comment]
I'm going to use ATOM to learn C++, so I didn't install PROS EDITOR.
![image](https://user-images.githubusercontent.com/33926386/33676665-54d7eaba-daf1-11e7-8307-49a39239081f.png)

**Comment by 3038922** [comment]
I installed EDITOR in my system to make mistakes. I can't use GCC-RUN and LINTER-GCC  as a compiler.

**Comment by 3038922** [comment]
![image](https://user-images.githubusercontent.com/33926386/33676992-407d581a-daf2-11e7-8e5d-81f031d958b6.png)
![image](https://user-images.githubusercontent.com/33926386/33677041-6afad144-daf2-11e7-9b69-04f972049e4e.png)

**Comment by 3038922** [comment]
![image](https://user-images.githubusercontent.com/33926386/33677180-e06fa54e-daf2-11e7-8386-a918eecda578.png)

**Comment by edjubuh** [comment]
> I can't use GCC-RUN and LINTER-GCC as a compiler.
We don't support those plugins. Using the PROS plugin will get you the ability to lint and build your projects.

I'm not sure how you have PROS installed anymore. Do you still not have the PROS Editor installed? If so, please install clang as mentioned [above](https://github.com/purduesigbots/pros-atom/issues/58#issuecomment-349721455).

**Comment by 3038922** [comment]
thank you .I solved the problem of AUTOCOMEPLE after I reinstalled.There are many junior high school students in China like PROS.Our teachers don't understand it very well. We need to study ourselves completely.We have finished the teaching of the official website, and hope to learn more.

**Comment by 3038922** [comment]
ouer team number is 7995A.

**Comment by edjubuh** [comment]
> There are many junior high school students in China like PROS.

Glad to hear that PROS is being used overseas! We're always looking to give students ready-to-use STEM skills!

> Our teachers don't understand it very well. We need to study ourselves completely.We have finished the teaching of the official website, and hope to learn more.

Feel free to submit suggestions/open issues on [purduesigbots/pros-docs](https://github.com/purduesigbots/pros-docs) if you'd like anything clarified.
