### ISSUE TITLE
How to update ATOM?

### ISSUE THREAD

**Issue by 3038922** [purduesigbots/pros-atom#61]
![image](https://user-images.githubusercontent.com/33926386/34513024-0190b718-f0a1-11e7-890a-152a46d8b976.png)
![image](https://user-images.githubusercontent.com/33926386/34513044-177b5ace-f0a1-11e7-841d-15e73dcd403d.png)
![image](https://user-images.githubusercontent.com/33926386/34513074-36024d0e-f0a1-11e7-9b3e-f7f475b6bfa1.png)
Maybe it's normal to upgrade ATOM LINTER.

**Comment by HotelCalifornia** [comment]
It looks like you're using the PROS Editor, which we maintain separately from the main Atom repository. In other words, we have the version pinned at 1.21.2 until we can merge in upstream changes.

**Comment by 3038922** [comment]
Thank you.
But I upgraded LINTER to make it impossible to display it normally.
