### ISSUE TITLE
Minor detail - PROS project icon

### ISSUE THREAD

**Issue by KZeronimo** [purduesigbots/pros-atom#65]
Very minor detail - more curious than anything (tried to correct with providing icon properties override in styles.less no luck)

#### Expected Behavior:
Project Icon for pros project sized appropriately

#### Actual Behavior:
pros project icon too large

#### Steps to reproduce:
Install Atom 
Install PROS utilizing Windows Installer (uncheck PROS editor)
Install PROS plugin `apm install file-icons linter tool-bar tool-bar-main busy build platformio-ide-terminal pros`
Create PROS project

#### System information:
Operating System (e.g. Windows, OS X, Ubuntu):
Window 10 1803

Atom Version:
1.28.2 x64
Plugin Version (PROS version):
0.7.4

#### Screenshots
<img width="318" alt="screen shot 2018-07-28 at 5 05 03 pm" src="https://user-images.githubusercontent.com/21271446/43360719-b83e7b32-9289-11e8-9613-db5de32f0b04.png">

**Comment by KZeronimo** [comment]
@edjubuh - I see file icon hack from purdueos.less was removed and I also see the `.pros-icon` is defined as an svg trace and that seems to be what is painting in the original screenshot I submitted - v0.7.5 of the plugin is still producing the original screenshot - is that the expected behavior?

I was hacking around and if I remove `.pros-icon` from purdueos.less then I observe the following which is what I would have expected (the PROS icons handled by [file-icons](https://github.com/file-icons/source/blob/master/charmap.md) `\EAAD`)

<img width="253" alt="screen shot 2018-07-30 at 2 32 57 pm" src="https://user-images.githubusercontent.com/21271446/43416697-02f4ae84-9407-11e8-875e-7da07e6d8967.png">

I'm not sure what the project pane is supposed to look like wrt to the icon for the pros file extension and I'm confident my hack is not the solution - just wanted to give you some more info - I know you guys have bigger fish to fry with v3 :)

Keep up the good work

**Comment by edjubuh** [comment]
Do I need to remove more than what I did in #66?

**Comment by KZeronimo** [comment]
I'm not intimate with how all the styling fits together; however, I do know that there are 2 classes defined in the `purdueos.less` file `.pros-icon` and `.pros-icon-bw`.  In my hacking I can say `.pros-icon` is producing the scalar graphic highlighted below

<img width="253" alt="43416697-02f4ae84-9407-11e8-875e-7da07e6d8967" src="https://user-images.githubusercontent.com/21271446/43421150-e07bb368-9413-11e8-8e14-983c4d296762.png">

Removing the `.pros-icon` class from `purdueos.less` produces the following

<img width="253" alt="43416697-02f4ae84-9407-11e8-875e-7da07e6d8967" src="https://user-images.githubusercontent.com/21271446/43420726-afa86840-9412-11e8-825c-9fecbb92f4e6.png">

If the sole purpose for that class definition in `purdueos.less` is to handle the file icon for .pros files then I think it would be safe to remove and let file-icons package handle the visual styling for .pros files - I'm just not sure if the `.pros-icon` class definition is used any place else

Hope that helps
