### ISSUE TITLE
Deprecation of path.dirname

### ISSUE THREAD

**Issue by aaronliu0130** [purduesigbots/pros-atom#68]
#### Expected Behavior:
Non
#### Actual Behavior:
Deprecated calls
pros (1 deprecation)
Check for UpdateDisable Package
Argument to path.dirname must be a string
Report Issue
Object.dirname - /Applications/Atom.app/Contents/Resources/app.asar/src/electron-shims.js:9:10
NewProjectModal.initialize - /Users/Aaron/.atom/packages/pros/lib/views/new-project.coffee:118:36
NewProjectModal.constructor - /Users/Aaron/.atom/packages/pros/node_modules/space-pen/lib/space-pen.js:184:25
new NewProjectModal - /Users/Aaron/.atom/packages/pros/lib/views/new-project.coffee:26:52
HTMLElement.PROS:New-Project - /Users/Aaron/.atom/packages/pros/lib/main.coffee:84:22
CommandRegistry.handleCommandEvent - <embedded>:24144:49

#### Steps to reproduce:
Don't know. Just ran int this "deprecation error".
#### System information:
Operating System (e.g. Windows, OS X, Ubuntu):
macOS Mojave Version 10.14 (18A391)
Atom Version:
1.31.2
Plugin Version (PROS version):
0.7.5
#### Screenshots
![image](https://user-images.githubusercontent.com/11874211/46580898-61b93900-ca60-11e8-8388-99072aac2a0b.png)
![image](https://user-images.githubusercontent.com/11874211/46580889-2585d880-ca60-11e8-808e-9830460adf8e.png)
![image](https://user-images.githubusercontent.com/11874211/46580891-33d3f480-ca60-11e8-94a3-36d2de462668.png)

**Comment by aaronliu0130** [comment]
When I pressed "Check for Update" in the Deprecation Cup, it said everything was up to date.
![image](https://user-images.githubusercontent.com/11874211/46580917-b066d300-ca60-11e8-844b-8d27565e0984.png)

**Comment by HotelCalifornia** [comment]
> why isn't it fixed on mac?

because it looks like this is being thrown from a different place than in #36. Either way, this can be safely ignored (and we're developing a new version of the atom plugin anyway, at purduesigbots/pros-atom3)
