### ISSUE TITLE
Link broken on "Getting started" page for Linux.

### ISSUE THREAD

**Issue by GLMONTER** [purduesigbots/pros-atom#69]
#### System information:
Operating System : Ubuntu

#### Additional Information

When I try to click the "Known Issue" Link on the getting started page for Linux, It doesn't open.

https://pros.cs.purdue.edu/cortex/getting-started/debian-linux.html

**Comment by baylessj** [comment]
Looks like we left off the `.html` suffix on the link, good catch. I'll go update that on the docs site, the changes should be live in the next 10-15 minutes.

**Comment by baylessj** [comment]
Closed by https://github.com/purduesigbots/pros-docs/commit/0f39d7434150d0b474608e1da1de4917b51bf5a0
